FROM node:18

WORKDIR /app

# Copy package files first for better caching
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Set environment
ENV NODE_ENV=development
ENV REACT_APP_NODE_ENV=development
ENV PORT=3000

# Command to run
CMD ["yarn", "start"]